---
- name: Build and Push Docker Images and then run this playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Build Backend Docker Image
      community.docker.docker_image:
        name: sanjeevy/code-backend1
        build:
          path: /root/cicdk8/
          dockerfile: Dockerfile.backend
        tag: latest
        push: true
        source: build
    - name: Build API Docker Image (Flask + Nginx)
      community.docker.docker_image:
        name: sanjeevy/api-backend1
        build:
          path: /root/cicdk8/
          dockerfile: Dockerfile.api
        tag: latest
        push: true
        source: build
    - name: Build Frontend Docker Image
      community.docker.docker_image:
        name: sanjeevy/frontend1
        build:
          path: /root/cicdk8/
          dockerfile: Dockerfile.frontend
        tag: latest
        push: true
        source: build
- name: Copy YAML files to K8s EC2 Node
  hosts: k8s
  tasks:
    - name: Copy YAML files to /home/ubuntu/
      copy:
        src: /root/cicdk8/k8/
        dest: /home/ubuntu/k8s/
        mode: '0644'
        remote_src: no

#- name: Apply Kubernetes Deployments from Ansible
#  hosts: k8s
#  become: yes
#  tasks:
#    - name: Apply backend deployment
#      shell: kubectl apply -f /home/ubuntu/k8s/backend-deployment.yml

#    - name: Apply frontend deployment
#      shell: kubectl apply -f /home/ubuntu/k8s/frontend-deployment.yml
